version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Asia/Tokyo
  groups:
    dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Asia/Tokyo
  groups:
    dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 10
