name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22.x ]
        os: [ ubuntu-latest ]
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: |
          go install gotest.tools/gotestsum@latest
          go get -v -t -d ./...

      - name: Test code
        run: gotestsum --junitfile unit-tests.xml -- -v -race ./...
